### ISSUE TITLE
Test in ST3

### ISSUE THREAD

**Issue by biannetta** [biannetta/MySublimeQL#2]
Test plugin in ST3 see if it still works alright

**Comment by perez-rich** [comment]
I've been testing this package in ST3 and I'm getting the below issue. The paths look correct so I'm not sure why I'm getting a Symbol not defined. Any ideas?

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
    'OperationalError', 'ProgrammingError', 'ROWID', 'STRING', 'TIME',
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/richard/Library/Application Support/Sublime Text 3/Packages/MySublimeQL/MySublimeQL.py", line 11, in <module>
    from MySQLdb import *
  File "/Users/richard/Library/Application Support/Sublime Text 3/Packages/MySublimeQL/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: dlopen(/Users/richard/Library/Application Support/Sublime Text 3/Packages/MySublimeQL/_mysql.so, 2): Symbol not found: _PyString_Type
  Referenced from: /Users/richard/Library/Application Support/Sublime Text 3/Packages/MySublimeQL/_mysql.so
  Expected in: flat namespace
 in /Users/richard/Library/Application Support/Sublime Text 3/Packages/MySublimeQL/_mysql.so
```
