### ISSUE TITLE
Error loading MySQL

### ISSUE THREAD

**Issue by mnpenner** [biannetta/MySublimeQL#6]
Plugin doesn't seem to work. When I pop open the Sublime terminal I see this:

```
Reloading plugin /home/me/.config/sublime-text-2/Packages/MySublimeQL/MySublimeQL.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./MySublimeQL.py", line 10, in <module>
    from MySQLdb import *
  File "./MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: ./_mysql.so: invalid ELF header
Reloading plugin /home/me/.config/sublime-text-2/Packages/MySublimeQL/_mysql.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
ImportError: ./_mysql.so: invalid ELF header
```

**Comment by biannetta** [comment]
What version of Sublime are you using

**Comment by mnpenner** [comment]
2.0.2, Build 2221.
